name: Close stale issues
on:
  # Allows you to dictate when you want this workflow to run using cron syntax (times in UTC)
  schedule:
    - cron: "0 15 * * *"
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4.1.1
        with:
          # The number of days without activity before the actions/stale action labels an issue
          days-before-issue-stale: 30
          # The number of days without activity before the actions/stale action closes an issue
          days-before-issue-close: 7
          # The label you want to apply to issues that have been inactive for the amount of time specified by days-before-issue-stale
          stale-issue-label: "stale"
          # The comment that you want to add to issues that are labeled by the actions/stale action
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          # The comment that you want to add to issues that are closed by the actions/stale action
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          # If you never want this action to label PRs, set this value to -1
          days-before-pr-stale: -1
          # If you never want this action to close PRs, set this value to -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
